[package]
name = "numbers_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "num"
path = "src/num.rs"

[dependencies]
[lib]
name = "handler"
path = "src/handler.rs"